### ISSUE TITLE
Rename output image file

### ISSUE THREAD

**Issue by nozzlegear** [Achno/gowall#22]
Hey! Great tool you've made. One small thing I'd like to see would be a way to rename the final image. Just as an example, I wanted to run one image through all of the available themes and get one file per theme: 

```fish
for theme in (gwall list)
  gowall convert -t "$theme" "$image"
end
```

But since gowall doesn't do any renaming, it just overwrites the output image file over and over. I had to adjust my script to copy the original image file, give it a unique name based on the theme, and then convert it with gowall. It wasn't difficult, but it'd be nice if gowall had some kind of `-o [filename]` option when working with one of the commands that writes files to the filesystem:

```fish
gowall convert -t "catppuccin" -o "my_catppuccin_image.png" "$image"
# I'm not sure how Go does string templates
gowall convert -t "$theme" -f "png" -o "$theme.{ext}" "$image"
gowall convert -t "$theme" -f "png" -o "$theme_{filename}.{ext}" --batch file1.png,file2.png
```

**Comment by Achno** [comment]
Hello there, thank you for the kind words

just having an `-o` option to specify the output name  on  convert,invert,pixelate etc...  is pretty easy to add.
Something like this: 
```bash
  gowall convert ~/img.png -t rose-pine -o out
```
```bash
for theme in (gwall list)
  gowall convert "$path" -t "$theme" -o "$theme"  
end
```
And the output should be : 
```
1. catppuccin.png
2. nord.png
3. rose-pine.png 
....
```

I will push it on main on `Saturday` probably, because i dont have any time this week, thanks for the suggestion.

**Comment by Achno** [comment]
Side note btw : I have already implemented color correction locally with Hald CLUT'S with rbf interpolation meaning
so the color correction algorithm will become a lot better removing `artifacts` `rough color transistions` etc...  and the time taken for converting an image will drop to ms from seconds.

So don't get discouraged if you dont like any conversions or if you see artifacts, i already have the solution i just need time to implement it in gowall

**Comment by Achno** [comment]
@nozzlegear just added it in this commit : b4956bf

You can now simply do 

```bash

#!/bin/bash

themes=$(gowall list)

input_path="/home/achno/Pictures/NOBORDER.png"

while IFS= read -r theme; do
  gowall convert "$input_path" -t "$theme" -o "$theme"
done <<< "$themes"
```

And the output should be :
```
1. catppuccin.png
2. nord.png
3. rose-pine.png 
....

**Comment by nozzlegear** [comment]
Awesome, thanks for the quick turnaround!
