### ISSUE TITLE
Unknown theme: catpuccin Error processing image : unknown theme

### ISSUE THREAD

**Issue by Packjackisback** [Achno/gowall#4]
gowall convert 07.jpg 
Processing single image...
Unknown theme: catpuccin
Error processing image : unknown theme

Not sure what happened, installed with go build manually

**Comment by Packjackisback** [comment]
This is most likely related to the fact that the .config directory is missing.

**Comment by Achno** [comment]
you misspelled, `catppuccin` with 2 p's is the actual name of the theme and you typed `catpuccin`

**Comment by Packjackisback** [comment]
Ah. I often misspell it too lol.
